# Spring Configuration
spring:
  # Servlet Multipart Configuration
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      
#gitHub credential to clone the template to local system
userName: "" # provide your userName
token: "" #provide your generated gitHub token

# Root Directory Configuration
rootDirectory: "/app/exavalu_mule_migration_enhancer/" # Path to the root directory
gitRepositoryUrl: "https://github.com/exavalu-solutions/mule-general-template.git" # Path to the mule general template 

scopes:
  mule3ApikitExceptionToErrorHandler: true
  idempotentXMLModifier: true
  roundrobinXMlModifier: true
  inboundOutboundProperties: true
  objectStoreModify:
    configureManagedStore: true
    configureObjectStore: true
  propertyModifier: true
  setSessionVariableToSetVariable: true
  validationXMLModifier: true
  vmqueue: true
  xmlCommentRemover: true
